### PR TITLE
Added support for IPv6 scoped addressing zone identifiers

### PR DESCRIPTION
**Pull request by pekkanikander**
Added support for IPv6 scoped address identifiers.  The URI_PARSE is also changed to be more strict with the interpretation of the sentence "[IPv6 literal] is the only place where square bracket characters are allowed in the URI syntax." of RFC 3986 Section 3.2.2.

I have tried to divide the changes into a series of smaller commits, to make reviewing easier.  It may be wise to squash them before merging.

The last commit f3c1670 rebuilds; it may need to be left out from merging.

### CODE REVIEW

**Comment by garycourt** [comment]
Thanks for this! I'll try to take a look at this this week. 
In the mean time, could you point me to the relevant RFC & section for IPv6 interface/zone identifiers?

**Comment by pekkanikander** [comment]
The relevant RFC is https://www.rfc-editor.org/rfc/rfc6874.txt   However, the best practise in many local contexts so far has been to allow also host parts of URIs in the form of `[ipv6-address%interface]`; only _with_ brackets.  The latter is what my patch supports, for parsing.  I presume the RFC formats of `[ipv6-address%25interface]` and `ipv6-address%25interface` should also be supported.  The latter may be somewhat tricky, though.

**Comment by pekkanikander** [comment]
Any progress with this one?  Anything you would like me to work on?  This week I ahve time.

**Comment by garycourt** [comment]
Ah, sorry man. I totally forgot about this job. And now I'm on vacation and
won't get to this for another 3 weeks. :-\

**Comment by garycourt** [comment]
I'm closing this PR as IPv6 Zone Identifiers has now been added.

**Pull request closed without merging**
